/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package villa;

import javax.swing.ImageIcon;

public class detailVillaFrame extends javax.swing.JFrame {
    
    private Villa villa;
    
    public detailVillaFrame() {
        this.villa = new Villa("", "", "", 0, "");
        initComponents();
    }
    
    public detailVillaFrame(String nama, String noTelp, String email, int villaId, String checkIn) {
        this.villa = new Villa(nama, noTelp, email, villaId, checkIn);
        initComponents();
    }
    
    public detailVillaFrame(Villa villa) { 
        this.villa = villa;
        initComponents();
        populateData();
    }
    
    public void setVilla(Villa villa) {
        this.villa = villa;
    }
    
    public Villa getVilla() {
        return villa;
    }
    
private void populateData() {
    VillaInfo villainfo = new VillaInfo() {
        @Override
        public String getImageLeft(int index) {
            return switch (index) {
                case 0 -> "/assets/villaSeruniLeft.jpg";
                case 1 -> "/assets/villaVictorianLeft.jpg";
                case 2 -> "/assets/villaNevadaLeft.jpg";
                default -> null;
            };
        }

        @Override
        public String getImageRight(int index) {
            return switch (index) {
                case 0 -> "/assets/villaSeruniRight.jpg";
                case 1 -> "/assets/villaVictorianRight.jpg";
                case 2 -> "/assets/villaNevadaRight.jpg";
                default -> null;
            };
        }
    };

    int villaIndex = villa.getVillaId() - 1;
    if (villaIndex >= 0 && villaIndex < villainfo.namaVilla.length) {
        txtNamaVilla.setText(villainfo.getNamaVilla(villaIndex));
        txtDeskripsi.setText(villainfo.getDeskripsiVilla(villaIndex));
        txtHarga.setText("Rp " + villainfo.getHargaVilla(villaIndex));
        imgLeft.setIcon(new ImageIcon(getClass().getResource(villainfo.getImageLeft(villaIndex))));
        imgRight.setIcon(new ImageIcon(getClass().getResource(villainfo.getImageRight(villaIndex))));
    } else {
        System.out.println("Invalid villa index.");
    }
}

        
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNamaVilla = new javax.swing.JLabel();
        imgLeft = new javax.swing.JLabel();
        imgRight = new javax.swing.JLabel();
        txtDeskripsi = new javax.swing.JLabel();
        txtHarga = new javax.swing.JLabel();
        btnPesan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        txtNamaVilla.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtNamaVilla.setForeground(new java.awt.Color(255, 255, 255));
        txtNamaVilla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNamaVilla.setText("Nama Villa");

        imgLeft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        imgRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtDeskripsi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtDeskripsi.setForeground(new java.awt.Color(255, 255, 255));
        txtDeskripsi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDeskripsi.setText("jLabel4");

        txtHarga.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtHarga.setForeground(new java.awt.Color(255, 255, 255));
        txtHarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHarga.setText("jLabel5");

        btnPesan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnPesan.setForeground(new java.awt.Color(51, 51, 51));
        btnPesan.setText("Pesan Sekarang");
        btnPesan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(imgLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(txtDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamaVilla, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)))))
                .addComponent(imgRight, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(txtNamaVilla)
                .addGap(18, 18, 18)
                .addComponent(txtDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHarga)
                .addGap(34, 34, 34)
                .addComponent(btnPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addComponent(imgRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(imgLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        // TODO add your handling code here:
        DataDiriFrame dataDiri = new DataDiriFrame(villa);
        dataDiri.setVisible(true);
        
        //Tutup Frame Saat ini
        this.dispose();
    }//GEN-LAST:event_btnPesanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detailVillaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detailVillaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detailVillaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detailVillaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detailVillaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesan;
    private javax.swing.JLabel imgLeft;
    private javax.swing.JLabel imgRight;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtDeskripsi;
    private javax.swing.JLabel txtHarga;
    private javax.swing.JLabel txtNamaVilla;
    // End of variables declaration//GEN-END:variables
}
